services:
  pulsar:
    image: apachepulsar/pulsar:3.2.0
    container_name: pulsar
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    volumes:
      - ./data:/opt/project/data
      - ./results:/opt/project/results
      - ./scripts:/opt/project/scripts   # <--- adicione isto
      - pulsar-data:/pulsar/data
    restart: unless-stopped

volumes:
  pulsar-data:
