version: "3.8"

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.5
    container_name: redpanda
    command:
      - redpanda
      - start
      - --kafka-addr
      - internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr
      - internal://redpanda:9092,external://localhost:19092
      - --mode
      - dev-container
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --overprovisioned
    ports:
      - "19092:19092" # para conectar de fora do container, se quiser
      - "9644:9644" # admin API (não é obrigatório pro teste)
    volumes:
      - .:/opt/project
      - redpanda_data:/var/lib/redpanda/data
    networks:
      - redpanda_net

networks:
  redpanda_net:
    driver: bridge

volumes:
  redpanda_data:
